### ISSUE TITLE
support older LSDJ version and littlefm

### ISSUE THREAD

**Issue by cyberic99** [jkotlinski/lsdpack#13]
Hi

I'm trying to convert some songs made with LSDJ 4.7.2 to .gbs, with no success.

My .gb file is 2.0MB in size, and is patched with littlefm.

I first opened the .gb file with gambatte, to create a .sav file, then launched lsdpack.

It generated 32 .s files, that were all 6 lines long.

So I downloaded lsdj-4.7.3, renamed my .sav to match the .gb filename, and launched lsspack again.

but I still got the same result.

So I'm wondering if older lsdj versions are supported (I hope so), and also if I missed some steps.

Also, is the ``H FF`` step still necessary, and does lsdpack use the .sav file or just the .gb ?

thanks for your answers!

**Comment by jkotlinski** [comment]
Hi!
I have tried it with lsdj 4.9.6 and that worked fine for me.
Yes, songs need to be stopped with HFF at the end of song.
If you want to, you could attach the .sav to this issue and I will take a look.

**Comment by jkotlinski** [comment]
From your description, it seems like something is perhaps wrong with the ROM+.sav you are trying to run.

Can you run the .gb in an emulator? Do the songs load and play OK?

**Comment by cyberic99** [comment]
I tried again and now I can correctly generate a .gbs file.
However it does not sound exactly like the original song.

I'll try to provide you with a small test song.

I'll open another issue, but this one can be closed.

Thank you!

**Comment by jkotlinski** [comment]
OK! At least it good that it works somewhat then........ I'll await the test song.
