### ISSUE TITLE
Assertion `false' failed in writer.cpp:283

### ISSUE THREAD

**Issue by cyberic99** [jkotlinski/lsdpack#14]
Hello

While testing a song conversion, I got an assertion failure, due to an unknown command, it seems.

I tried to isolate the problem to a small section of the song.

Here are the relevant files:
[assert_failed.zip](https://github.com/jkotlinski/lsdpack/files/5974709/assert_failed.zip)

I run lsdpack on linux, at latest commit: 35da60cb

Thank you

**Comment by jkotlinski** [comment]
Oops! Sorry about that!

**Comment by cyberic99** [comment]
no pb, and thank you!
