### ISSUE TITLE
feature request: raw register dump

### ISSUE THREAD

**Issue by cyberic99** [jkotlinski/lsdpack#16]
It could be interesting to get a raw register dump  of a song in text form, a bit like what vgm2txt does:
```
<cycle> <address> <value>
or
<address> <value>
<wait x cycles>
...
```

This could be useful, in order to analyze some songs

An option to choose if we want the 'optimized' (without redundant reg writes) or the raw dump could be useful too.

**Comment by cyberic99** [comment]
thanks @jkotlinski 

I edited the issue text, some of it was previously hidden

would it be possible to get some timing or clock information when writing the register, in raw mode?

**Comment by jkotlinski** [comment]
Ah! The player is not cycle exact, so I cannot give cycles.

What you can get already is to look for FLAG_END_TICK or CMD_END_TICK. Either of those will end a tick. Ticks are fired six times/screen update.

**Comment by cyberic99** [comment]
> Ah! The player is not cycle exact, so I cannot give cycles.

allright, but libgambatte is!

I had a patch against an old version of lsdpack that did convey the cycles information and printed it.
But lsdpack has changed a lot (for the better) since ;-)

**Comment by jkotlinski** [comment]
Oh, that’s interesting. Well, if you like to contribute something like
that, it’s welcome.
Would the -r flag to disable optimizations still be useful on its own or
could it just as well be removed?

**Comment by cyberic99** [comment]
Ok then, I'll try to rebase my patch.

> Would the -r flag to disable optimizations still be useful on its own

I think so, now that you have it and it doesn't increase the code complexity too much, let's keep it

**Comment by cyberic99** [comment]
Hello Johan, here is the pull request: https://github.com/jkotlinski/lsdpack/pull/17

At least 2 problems are remaining:
- there seem to be 35s of silence at the start of the song, before getting any sound
- the cycles seem to elapse 2 times slower than expected

And also, optimizations are disabled.
we could run an optimization pass, but it would require a change to the ``music_stream`` vector, and would be a pretty big change.

What do you think @jkotlinski ?
