### ISSUE TITLE
RGBDS doesn't like size of some lsdpack songs

### ISSUE THREAD

**Issue by urbster1** [jkotlinski/lsdpack#2]
Using lsdpack on Windows x64 with RGBDS 0.3.7 gives this error with the following files:
`ERROR: lsdj496_aq.s(163804):`
`    Section 'MUSIC_10' is too big (max size = 0x4000 bytes).`
[lsdj496_aq.zip](https://github.com/jkotlinski/lsdpack/files/2502096/lsdj496_aq.zip)

**Comment by urbster1** [comment]
compiling however does work with commit# 223768726fb2e9d1d5ea3dad211ad37b025c6560

**Comment by jkotlinski** [comment]
Should be fixed in master - could you verify?

**Comment by urbster1** [comment]
Yes! Tested and working properly now, thanks!

**Comment by jkotlinski** [comment]
💯
