### ISSUE TITLE
generated .gbs files sound incorrect

### ISSUE THREAD

**Issue by cyberic99** [jkotlinski/lsdpack#20]
Hi,

I tried to generate .gbs files from some of our songs.

Some of them sound more or less different than the song played in lsdj.

For instance, here is a .sav file with a short intro on noise channel.

[noise_opt.zip](https://github.com/jkotlinski/lsdpack/files/6306892/noise_opt.zip)

If I comment all rules in ``writer.cpp::optimize_music_stream()``, the .gbs sounds right (noise_ok.gbs)

but with optimizations, it sound incorrect (noise_nok.gbs).

Both .gbs files and the .sav are in the zip.

I tested it with lsdj 4.7.3

Thank you!

**Comment by jkotlinski** [comment]
Could it be a player issue? When I generate a .gb file and play it back, it sounds OK on my DMG.

**Comment by cyberic99** [comment]
OK I'll try to do that

I thought that generating a .gbs was easier to do and to test.

can you confirm that registers optimisations are done also when generating .gb files ?

**Comment by cyberic99** [comment]
maybe it is a specific .gbs issue...

For now I reduced the test to the noise channnel, but with rhe wav channel, the result is even worse... but if I disable the optimisations the result is correct

**Comment by jkotlinski** [comment]
I don’t know.
What happens if you use gbs2gb to convert the gbs to gb, then play it on
real hardware?

**Comment by cyberic99** [comment]
I converted then tested both roms on a GBA.
The 'nok' still sounds incorrect, and the 'ok' sounds fine

**Comment by jkotlinski** [comment]
OK, I think I hear the difference now - I was confused by a bug in Sameboy.
It seems enough to comment out `optimize_rule(noi_length);` ?
If you agree, I will push that change.
