### ISSUE TITLE
wave channel seems to pitch shift down after conversion

### ISSUE THREAD

**Issue by dm-colin** [jkotlinski/lsdpack#23]
[lsdj.sav.zip](https://github.com/jkotlinski/lsdpack/files/6806069/lsdj.sav.zip) (v8.5.1)
[lsdj-7_0_2.sav.zip](https://github.com/jkotlinski/lsdpack/files/6806106/lsdj-7_0_2.sav.zip) (v7.0.2)

Following steps from the README:
```
$ lsdpack -g lsdj-7_0_2.gb
.gbs mode enabled
Loaded lsdj-7_0_2.gb
Playing song 1...
Recording to 'lsdj-7_0_2-1.s'
Wrote 16 samples
Song 1: 266 bytes
OK
$ rgbasm -o lsdj-7_0_2-1.o lsdj-7_0_2-1.s
$ rgblink -o player-1.gb boot.o player.o lsdj-7_0_2-1.o
$ rgbfix -v -m 0x19 -p 0xff player-1.gb
$
```

Running the result in emulator results in something very pitch-shifted down.

Tested with:
- Big Sur
- rgbds v0.5.1
- lsdj v8.5.1 (lsdj.sav.zip) and lsdj v7.0.2 (lsdf-7_0_2.sav.zip)
- OpenEmu's gameboy emulator which seems to be Gambatte

I can post MP3s of what I'm expecting vs what I'm hearing if needed.

Commenting out the body of the transform function in https://github.com/jkotlinski/lsdpack/blob/master/rules/rule_pitch.cpp seems to handle this issue.

**Comment by jkotlinski** [comment]
should be fine now, thanks for report!
