### ISSUE TITLE
.gbs build instructions?

### ISSUE THREAD

**Issue by mbodomi** [jkotlinski/lsdpack#4]
You could add description for outputting GBS

**Comment by jkotlinski** [comment]
It would be possible to make another player that supports .gbs, and a .gbs
header generator. Although I’m puzzled why anyone would like to use .gbs in
this day and age..? .mp3 is a lot more practical?

**Comment by mbodomi** [comment]
For eg. making a tiny game, w/ gbs playback instead of mp3 or ogg.
Or a multiplatform oldskool musicdisk.
Or just for the sake of adding modules to modland.

**Comment by Eiyeron** [comment]
Or play the same looped track for hours without the intro/fadeout nor busting one's own internet data quota with "10 hour" music videos on youtube.

**Comment by jkotlinski** [comment]
Which GBS playback library/program would you recommend for testing?

**Comment by cyberic99** [comment]
[gbsplay](https://github.com/mmitch/gbsplay) is nice and also has a plugin to produce register dumps

**Comment by Eiyeron** [comment]
I'm partial to Losnoco's Foobar2000 [plugins](https://github.com/losnoco/) as they support *a lot* of formats, but I don't know about their accuracy. Foobar allows for quick converting, so it might be interesting to look at it to export and compare audio dumps.

**Comment by Pegmode** [comment]
I gave conversions from lsdpack a go. Since the .gbs does not support the LYC interrupt I ported it to the Timer interrupt.  Ran into some issues with the exported gbs. I'm able to get the .gbs playing but it has issues. The compiled ROM works but not the .gbs. The behavior matches what happens with the ROM when there is no MBC present so I think there may be issues with bank switching in the .gbs but I don't have a concrete way to test this. [progress](https://github.com/Pegmode/lsdPack2GBS)

**Comment by jkotlinski** [comment]
@Pegmode nice effort! hope it can be made to work all the way!

**Comment by cyberic99** [comment]
Nice idea @Pegmode ! maybe you can get help from people developing gbsplay.
Recently, they added support for playing gameboy .vgm files, where they generate gb assembly on the fly depending on the .vgm file content: https://github.com/mmitch/gbsplay/commit/53f353f096c7ade2b000fbad4c3c1fdb7a299785

**Comment by jkotlinski** [comment]
Looking at things closer, the .gbs problems are very likely because MBC5 bank switching is not supported.
A simple thing to try for the .gbs converter would be to comment out all writes to $3000 from the player.
Sadly, by doing this, it's likely each .gbs would only fit a single song, if even that.

**Comment by jkotlinski** [comment]
A simple thing to try for the .gbs converter would be to comment out all writes to $3000 from the player. These are not supported with standard .gbs bank switching and will cause problems.

**Comment by jkotlinski** [comment]
Actually .gbs seems like it works ok now! Added instructions how to build .gbs to README.md

**Comment by mbodomi** [comment]
https://gitee.com/matuska-b-m/lsdsng-to-gbs-renders/
c'mon people lets do this!
