### ISSUE TITLE
Nothing written to .s file

### ISSUE THREAD

**Issue by rablador** [jkotlinski/lsdpack#7]
I cannot get anything written to the .s file. Either I get the following:

```
./lsdpack lsdj.gb
Recording to 'lsdj.s'
Loading lsdj.gb...
Song 1...
wrote 128 sample bytes, 73399 music bytes
Song 2...
wrote 0 sample bytes, 73457 music bytes
Song 3...
wrote 0 sample bytes, 73391 music bytes
Song 4...
wrote 0 sample bytes, 73352 music bytes
Song 5...
wrote 0 sample bytes, 73321 music bytes
Song 6...
wrote 0 sample bytes, 73363 music bytes
Song 7...
wrote 0 sample bytes, 73430 music bytes
Song 8...
Song 9...
Song 10...
Song 11...
```
...etc etc. Or it just hangs on the first part:

```
./lsdpack lsdj.gb
Recording to 'lsdj.s'
Loading lsdj.gb...
Song 1...
```

This happens depending on the sav file I'm using, but neither results in a non-empty .s file. I built the lsdpack with cmake on Mac and have a lsdj.gb and lsdj.sav in the same folder.

**Comment by jkotlinski** [comment]
Hi!
Did you make sure all saved songs are stopped by a HFF command? If not,
they will loop forever.

**Comment by rablador** [comment]
I did, by putting an empty phrase with HFF at the top in all four channels.

**Comment by rablador** [comment]
One weird thing though. When I check the songs with lsdpatch it seems they have been corrupted (?) or something. This happens only after they have been played with SameBoy first.

<img width="326" alt="Screenshot 2020-11-21 at 20 18 38" src="https://user-images.githubusercontent.com/1230209/99885627-bf0ba680-2c36-11eb-8370-8537691b5ca7.png">

I have tried with untouched saves as well (pulled directly from and flash cart), but same end result.

**Comment by jkotlinski** [comment]
That’s interesting. Could you attach the .sav file and I’ll have a look?
Thanks!

**Comment by rablador** [comment]
Sure thing! LSDJ version is 8.9.6.

(this sav looks clean i lsdpatch)
[lsdj.sav.zip](https://github.com/jkotlinski/lsdpack/files/5578254/lsdj.sav.zip)

**Comment by rablador** [comment]
Hmm, maybe I was wrong about SameBoy. This one looks corrupted, but it was in fact directly pulled for an El Cheapo cart by BennVenn. It has not been prepared with HFF.

[LSDJ1A8F.sav.zip](https://github.com/jkotlinski/lsdpack/files/5578261/LSDJ1A8F.sav.zip)

**Comment by jkotlinski** [comment]
It looks like both those .savs are unwell. If I open them up using BGB, and go to Project screen in LSDj, there is no load/save file button. Maybe they did not transfer correctly?

**Comment by rablador** [comment]
Ah! I have seen that on emulators as well, but I always thought it had to do with not running on real hardware. I dumped the same save with new config and it displayed correctly in the project screen. Works with lsdpack as well! Thanks a bunch! :D
