### ISSUE TITLE
Static noise and flickering

### ISSUE THREAD

**Issue by rablador** [jkotlinski/lsdpack#9]
Hi!

I get static noise and flickering when following the instructions to compile a .gb rom with the player.s and boot.s (it seems to run "correctly" otherwise). There's no audio in the video below, but unless I'm mistaken the flickering coincides with the noise.

[Screen Recording 2020-11-22 at 11.50.37.mov.zip](https://github.com/jkotlinski/lsdpack/files/5579350/Screen.Recording.2020-11-22.at.11.50.37.mov.zip)

Unfortunately I don't speak assembly very well, but here's the full set of files used (original lsdj.gb, save, assembly files etc):

[flicker_and_static_src.zip](https://github.com/jkotlinski/lsdpack/files/5579351/flicker_and_static_src.zip)

**Comment by jkotlinski** [comment]
Hi! It's likely because of issue #8 . I should try to fix that.

**Comment by jkotlinski** [comment]
I pushed a fix to master now, could you tell if it works for you?
A word of caution, it will not sound OK on all emulators. But it should be fine in e.g. Gambatte and SameBoy.

**Comment by rablador** [comment]
It is indeed better, but stills flickers a little. I get the best result with Gambatte, but Sameboy works ok as well. GBA mode i Sameboy sounds weird though, with white noise at the end of the song. Guess it doesn't matter much, but thought I should report since I happened to stumble upon it.

**Comment by jkotlinski** [comment]
The flicker you notice is normal and indicates varying CPU usage as the
song is being played back. The code that draws the bars is intended to be
replaced by user :-)

**Comment by rablador** [comment]
Ah well, guess I'll have to learn some assembly then. Thanks for the fix! :)

**Comment by jkotlinski** [comment]
Cool! Let me know if you need any help or pointers!
